version: '3.9'

services:
  migrate:
    image: migrate/migrate:v3.5.4
    volumes:
      - ./internal/migrations:/migrations
    command: 
      - "-path=/migrations"
      - "-database=postgres://partsbot:partsbot@postgres:5432/partsbot?sslmode=disable"
      - "up"
    depends_on:
      postgres:
        condition: service_healthy

  app:
    build: .
    container_name: partsbot_app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://partsbot:partsbot@postgres:5432/partsbot?sslmode=disable
      - TELEGRAM_TOKEN=8481467325:AAGh_hIif7sLXZsgTY3WqZZKvJHGcL5behI
      - PART_API=5c52f6e4db91259648e10e3dfab5828e
      - PART_API_VIN=5cdb1bdd38ea05fb81466bafb1d86efb
      - PART_API_TREE=01186691560aa5dbda9f7be1c2dcc7ec
      - VK_API=vk1.a.z5JLTfp8efGsKWoVdHtvvFS3ImAimXNZMOs3KAnlUfV3lEUjh2YNo9E9jzWGI3oC9ATo-n_EO7UCh_WRN1m3yt2ZRZuqyVKnMNTckRlEBE1AnzbJ32F8I6rEpDJw8icZkTBLUBl6eQ3bdoK0NLUXOJ5fTmI3TW336FoYKFTurvRgg5k8IDPtiEOrky_DO8nEVpWDRw91_hXTqM6qkmY7cQ
      - GROUP_ID=237413680
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  postgres:
    image: postgres:16
    container_name: partsbot_db
    environment:
      POSTGRES_USER: partsbot
      POSTGRES_PASSWORD: partsbot
      POSTGRES_DB: partsbot
      POSTGRES_INITDB_ARGS: --auth-host=md5  
    ports:
      - "5432:5432"
    #volumes:
      #- postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U partsbot"]
      interval: 5s
      timeout: 5s
      retries: 5

#volumes:
#  postgres_data: