package errors

import "errors"

var (
	ErrNameCanNotBeNull       = errors.New("название авто не может быть пустым")
	ErrVinMustBe17            = errors.New("вин код должен состоять из 17 символов (английские буквы!)")
	ErrCarId                  = errors.New("car id is too short/long")
	ErrUserId                 = errors.New("user id is too short/long")
	ErrItemName               = errors.New("product name is too long/short")
	ErrItemBrand              = errors.New("brand name is too long/short")
	ErrItemPartID             = errors.New("part ID is too long/short")
	ErrItemPrice              = errors.New("product price is negative/too high")
	ErrItemQuantity           = errors.New("quantity of the product is negative/too large")
	ErrUserName               = errors.New("user name is too short/long")
	ErrUserPhone              = errors.New("user phone is too short/long")
	ErrId                     = errors.New("user id is too short/long")
	ErrTgId                   = errors.New("user tg id is too short/long")
	ErrAmountCanNotBeNull     = errors.New("amount cant be null")
	ErrOrderEmpty             = errors.New("order cant be empty")
	ErrAddressEmpty           = errors.New("address can not be empty")
	ErrCartIsEmpty            = errors.New("cart empty")
	ErrDelivDay               = errors.New("delivery day cant be negative")
	ErrItemNotFound           = errors.New("item not found")
	ErrInvalidPassword        = errors.New("invalid password")
	ErrInvalidEmail           = errors.New("invalid email")
	ErrInvalidCredentials     = errors.New("invalid credentials")
	ErrInvalidPaymentProvider = errors.New("invalid provider")
	ErrInvalidPaymentURL      = errors.New("invalid provider payment url")
	ErrInvalidProviderTxnID   = errors.New("invalid provider transaction id")
)
